### ISSUE TITLE
boolean filters not compatible with postgres DB

### ISSUE THREAD

**Issue by 2mt-bornscheuer** [monterhealth/api-filter-bundle#14]
When using boolean filters, in the resulting query to the database, integers are used.
The query parameter can be written as an integer or a boolean, but that does not change the resulting database query.
Since postgres always expects a boolean value, there is currently no way to use boolean filters with a posgres database (unless i missed something?).
I am, using version 2.1 of the bundle in a symfony 7.1 project, with postgres version 16.

**Comment by monterhealth** [comment]
@2mt-bornscheuer Thanks. The filter will now always use true and false instead of 1 and 0.
