### ISSUE TITLE
Filtering on table that has no direct relationship by using join

### ISSUE THREAD

**Issue by Rubc** [monterhealth/api-filter-bundle#3]
For example:

We want to filter on properties in the component entity that is joined.

 $queryBuilder
            ->select(['device', 'component'])
            ->from(Device::class, 'device')
            ->leftJoin(Component::class, 'component', Join::WITH, 'device.hostname = component.hostname')
        ;
$this->monterHealthApiFilter->addFilterConstraints($queryBuilder, Device::class, $request->query);
$this->monterHealthApiFilter->addFilterConstraints($queryBuilder, CmdbComponent::class, $request->query);

We defined the ApiFilters on the Component class like this:

    /**
     * @var string
     *
     * @ORM\Column(name="organization", type="string", length=255, nullable=true)
     * @ApiFilter(SearchFilter::class)
     */
    private $organization;

When adding this query param to the API call: /?component:organization=Test,
the filters are not applied. is there a way that we can use filters on a joined table?

**Comment by fd6130** [comment]
You need to apply filter in Device class for component property:

```php

/**
* @ORM\.....
*
* @ApiFilter(SearchFilter::class, properties={"organization"})
*/
private $component;
```

And use repository: 

```php
$qb = $deviceRepository->createQueryBuilder('qb');
$this->monterHealthApiFilter->addFilterConstraints($qb, $qb->getClassName(),  $request->query);
```
Join will be applied when you filter it by query string:

```
/?component:organization=Test
```

It will left join / join the device with component.

**Comment by Rubc** [comment]
@fd6130 thanks for your comment but there is no component property in the Device Class. Hence why we do a left join by doing this: ->leftJoin(Component::class, 'component', Join::WITH, 'device.hostname = component.hostname')

Is there a way to filter on component:organization=Test when the component property is not on the Device class?

**Comment by fd6130** [comment]
> @fd6130 thanks for your comment but there is no component property in the Device Class. Hence why we do a left join by doing this: ->leftJoin(Component::class, 'component', Join::WITH, 'device.hostname = component.hostname')
> 
> Is there a way to filter on component:organization=Test when the component property is not on the Device class?

Currently i don't think we have a way for that. Perhaps you need to add bidirectional relation for Device and Component. Or you might need to write your own filter for your usage.

**Comment by Rubc** [comment]
I will try that, thanks!

**Comment by fd6130** [comment]
> I will try that, thanks!

Any feedback from this issue?
