### ISSUE TITLE
Using attribute instead of annotation

### ISSUE THREAD

**Issue by fd6130** [monterhealth/api-filter-bundle#5]
Since PHP 8 support attribute, maybe we can consider to support attribute as well? I wonder will it clash with annotation?

```php
#[ApiFilter(SearchFilter::class, properties: ["id"])]
class Product
{
   #[ApiFilter(SearchFilter::class)]
   private $id;
}
```

**Comment by Simopich** [comment]
Hi @fd6130, I've added attributes support in my fork of the repo and I've sent a pull request to @monterhealth .

#12

**Comment by monterhealth** [comment]
Hi @Simopich, thanks for the changes. It works perfect. I finally found time to review the code and merge it into the repo.

**Comment by Simopich** [comment]
It was a pleasure :)
I'll be happy to contribute again in case needed, cheers!

**Comment by monterhealth** [comment]
That would be great, cheers!
